apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: readers-haven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: readers-haven-payment-service:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 5010
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: PORT
          value: "5010"
        - name: PAYMENT_PROCESSING_DELAY_MS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_PROCESSING_DELAY_MS
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5010
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5010
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: readers-haven
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5010"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: payment-service
  ports:
  - name: http
    port: 5010
    targetPort: http
